### ISSUE TITLE
When I run make I got an error.

### ISSUE THREAD

**Issue by ghost** [0x09/dspfun#1]
After I run make in dspfun directory i got:

home/dspfun$ make
make -C spec
make[1]: Entering directory 'home/dspfun/spec'
cc -std=c11 -Ofast -I../include/ -D_GNU_SOURCE -DMAGICKWAND_VERSION=6  -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -lMagickWand-6.Q16 -lMagickCore-6.Q16 -lfftw3 -lm -o spec spec.c
In file included from spec.c:6:0:
spec.h: In function ‘spec_args’:
spec.h:101:5: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
     asprintf(&opts.help,"-g -c csp -t (%s) -R (%s) -T (%s) -S (%s) -G (%s(float)) ",
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              enum_keys(spectype),enum_keys(rangetype),enum_keys(scaletype),enum_keys(signtype),enum_keys(gaintype));
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/ccIj1v55.o: In function `main':
spec.c:(.text.startup+0x516): undefined reference to `MagickWandGenesis'
spec.c:(.text.startup+0x51b): undefined reference to `NewMagickWand'
spec.c:(.text.startup+0x529): undefined reference to `MagickReadImage'
spec.c:(.text.startup+0x531): undefined reference to `MagickGetImageWidth'
spec.c:(.text.startup+0x543): undefined reference to `MagickGetImageHeight'
spec.c:(.text.startup+0x598): undefined reference to `fftw_alloc_real'
spec.c:(.text.startup+0x5bf): undefined reference to `MagickExportImagePixels'
spec.c:(.text.startup+0x5c7): undefined reference to `DestroyMagickWand'
spec.c:(.text.startup+0x613): undefined reference to `fftw_plan_many_r2r'
spec.c:(.text.startup+0x622): undefined reference to `fftw_execute'
spec.c:(.text.startup+0x632): undefined reference to `fftw_destroy_plan'
spec.c:(.text.startup+0x95f): undefined reference to `NewMagickWand'
spec.c:(.text.startup+0x988): undefined reference to `MagickConstituteImage'
spec.c:(.text.startup+0x990): undefined reference to `fftw_free'
spec.c:(.text.startup+0xcb6): undefined reference to `MagickSetImageProperty'
spec.c:(.text.startup+0xcc5): undefined reference to `MagickWriteImage'
spec.c:(.text.startup+0xccd): undefined reference to `DestroyMagickWand'
spec.c:(.text.startup+0xcd2): undefined reference to `MagickWandTerminus'
spec.c:(.text.startup+0xdfa): undefined reference to `log1p'
spec.c:(.text.startup+0xe7a): undefined reference to `log1pl'
spec.c:(.text.startup+0xf07): undefined reference to `MagickTransformImageColorspace'
collect2: error: ld returned 1 exit status
Makefile:10: recipe for target 'spec' failed
make[1]: *** [spec] Error 1
make[1]: Leaving directory home/dspfun/spec'
Makefile:8: recipe for target 'spec' failed
make: *** [spec] Error 2

I have installed  FFTW, ImageMagick.

**Comment by 0x09** [comment]
Hi @volodymyrkepsha, thanks for reporting. This is happening because GNU ld expects libraries to be positioned *after* the source file in the actual `cc` invocation, which isn't what the Makefile is doing here.
Should be fixed for all of the projects with e8dc0e7b9f675e85fc13d1ffe602beeaf233b49b, can you pull and try running `make` again?

**Comment by ghost** [comment]
Thanks for a quick reply.
Now I got this:


make -C spec
make[1]: Entering directory '/home/volodymyr/dspfun/spec'
cc -std=c11 -Ofast -I../include/ -D_GNU_SOURCE -DMAGICKWAND_VERSION=6  -o spec spec.c -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -lMagickWand-6.Q16 -lMagickCore-6.Q16 -lfftw3 -lm
In file included from spec.c:6:0:
spec.h: In function ‘spec_args’:
spec.h:101:5: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
     asprintf(&opts.help,"-g -c csp -t (%s) -R (%s) -T (%s) -S (%s) -G (%s(float)) ",
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              enum_keys(spectype),enum_keys(rangetype),enum_keys(scaletype),enum_keys(signtype),enum_keys(gaintype));
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc -std=c11 -Ofast -I../include/ -D_GNU_SOURCE -DMAGICKWAND_VERSION=6  -o ispec ispec.c -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -lMagickWand-6.Q16 -lMagickCore-6.Q16 -lfftw3 -lm
In file included from ispec.c:6:0:
spec.h: In function ‘spec_args’:
spec.h:101:5: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
     asprintf(&opts.help,"-g -c csp -t (%s) -R (%s) -T (%s) -S (%s) -G (%s(float)) ",
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              enum_keys(spectype),enum_keys(rangetype),enum_keys(scaletype),enum_keys(signtype),enum_keys(gaintype));
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: Leaving directory '/home/volodymyr/dspfun/spec'
make -C motion
make[1]: Entering directory '/home/volodymyr/dspfun/motion'
cc -std=c11 -Ofast -Wno-initializer-overrides -I../include  -c -o ffapi.o ../include/ffapi.c
../include/ffapi.c: In function ‘ffapi_io_close_pipe’:
../include/ffapi.c:281:3: warning: implicit declaration of function ‘pclose’; did you mean ‘fclose’? [-Wimplicit-function-declaration]
   pclose((FILE*)s->opaque);
   ^~~~~~
   fclose
../include/ffapi.c: In function ‘ffapi_open_output’:
../include/ffapi.c:314:76: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘url’
   enc = avcodec_find_encoder(av_guess_codec(out->fmt->oformat,NULL,out->fmt->url,NULL,AVMEDIA_TYPE_VIDEO));
                                                                            ^~
../include/ffapi.c:342:3: warning: implicit declaration of function ‘asprintf’; did you mean ‘vsprintf’? [-Wimplicit-function-declaration]
   asprintf(&cmd,
   ^~~~~~~~
   vsprintf
../include/ffapi.c:354:27: warning: implicit declaration of function ‘popen’; did you mean ‘fopen’? [-Wimplicit-function-declaration]
   if(!(out->fmt->opaque = popen(cmd,"w"))) {
                           ^~~~~
                           fopen
../include/ffapi.c:354:25: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   if(!(out->fmt->opaque = popen(cmd,"w"))) {
                         ^
../include/ffapi.c:360:12: warning: implicit declaration of function ‘fileno’; did you mean ‘mblen’? [-Wimplicit-function-declaration]
   int fd = fileno((FILE*)out->fmt->opaque);
            ^~~~~~
            mblen
../include/ffapi.c:361:19: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘url’
   av_free(out->fmt->url);
                   ^~
../include/ffapi.c:362:11: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘url’
   out->fmt->url = av_asprintf("pipe:%d",fd);
           ^~
../include/ffapi.c:365:38: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘url’
  if(avio_open2(&out->fmt->pb,out->fmt->url,AVIO_FLAG_WRITE,NULL,&opts))
                                      ^~
../include/ffapi.c:371:36: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘url’
  av_dump_format(out->fmt,0,out->fmt->url,1);
                                    ^~
../include/ffapi.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-initializer-overrides’
Makefile:8: recipe for target 'ffapi.o' failed
make[1]: *** [ffapi.o] Error 1
make[1]: Leaving directory '/home/volodymyr/dspfun/motion'
Makefile:8: recipe for target

Can it be due to my environment ?

**Comment by 0x09** [comment]
Is it possible to update your version of the FFmpeg libraries? The url field which the errors are referencing was added / its predecessor deprecated in libavformat v 58.7.100 (included in the FFmpeg 4.0 release).

The other warnings seem to be due to glibc needing `_GNU_SOURCE` defined in order to make those functions available, so I'll just add this to the Makefile. For now you can get around it with `CFLAGS=-D_GNU_SOURCE make`.

**Comment by ghost** [comment]
Yes, I updated the ffmpeg and used the flag which you suggested
Now I got this: 
```
volodymyr@volodymyr:~/Desktop/Teezily/dspfun$ CFLAGS=-D_GNU_SOURCE make
make -C spec
make[1]: Entering directory '/home/volodymyr/Desktop/Teezily/dspfun/spec'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/volodymyr/Desktop/Teezily/dspfun/spec'
make -C motion
make[1]: Entering directory '/home/volodymyr/Desktop/Teezily/dspfun/motion'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/volodymyr/Desktop/Teezily/dspfun/motion'
make -C applybasis
make[1]: Entering directory '/home/volodymyr/Desktop/Teezily/dspfun/applybasis'
cc -std=c11 -Ofast -DMAGICKWAND_VERSION=6 -D_GNU_SOURCE -lfftw3f -o draw draw.c -I../include -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -lMagickWand-6.Q16 -lMagickCore-6.Q16 -lm
/tmp/ccdgPF0a.o: In function `main':
draw.c:(.text.startup+0x1b5): undefined reference to `fftwf_malloc'
draw.c:(.text.startup+0x257): undefined reference to `fftwf_plan_r2r_2d'
draw.c:(.text.startup+0x262): undefined reference to `fftwf_execute'
draw.c:(.text.startup+0x26a): undefined reference to `fftwf_destroy_plan'
draw.c:(.text.startup+0x2bb): undefined reference to `fftwf_free'
draw.c:(.text.startup+0x2c0): undefined reference to `fftwf_cleanup'
draw.c:(.text.startup+0x2fa): undefined reference to `fftwf_malloc'
collect2: error: ld returned 1 exit status
Makefile:14: recipe for target 'draw' failed
make[1]: *** [draw] Error 1
make[1]: Leaving directory '/home/volodymyr/Desktop/Teezily/dspfun/applybasis'
Makefile:8: recipe for target 'applybasis' failed
make: *** [applybasis] Error 2

```

I guess we are getting closer to solution.

**Comment by 0x09** [comment]
Ah, this was a left over instance of the same problem as above -- -lfftw3f is still positioned to the left of the output when compiling draw.c.
Fixed with https://github.com/0x09/dspfun/commit/319aeb369d1d0e2876be80d629c38aa1bb0f1a69

**Comment by ghost** [comment]
Thanks for the update, but I'm still struggling.

```
volodymyr@volodymyr:~/Desktop/Teezily/dspfun$ sudo make
[sudo] password for volodymyr: 
make -C spec
make[1]: Entering directory '/home/volodymyr/Desktop/Teezily/dspfun/spec'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/volodymyr/Desktop/Teezily/dspfun/spec'
make -C motion
make[1]: Entering directory '/home/volodymyr/Desktop/Teezily/dspfun/motion'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/volodymyr/Desktop/Teezily/dspfun/motion'
make -C applybasis
make[1]: Entering directory '/home/volodymyr/Desktop/Teezily/dspfun/applybasis'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/volodymyr/Desktop/Teezily/dspfun/applybasis'
make -C zoom
make[1]: Entering directory '/home/volodymyr/Desktop/Teezily/dspfun/zoom'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/volodymyr/Desktop/Teezily/dspfun/zoom'
make -C scan
make[1]: Entering directory '/home/volodymyr/Desktop/Teezily/dspfun/scan'
cc -DPRECISION=F -Wno-initializer-overrides -std=c11 -Ofast -flto -I../include  -DMAGICKWAND_VERSION=6 -c -o speclib.o ../include/speclib.c
../include/speclib.c: In function ‘spec_params_parse’:
../include/speclib.c:58:20: warning: implicit declaration of function ‘strdup’; did you mean ‘strcmp’? [-Wimplicit-function-declaration]
  char* key,* buf = strdup(options),* string = buf;
                    ^~~~~~
                    strcmp
../include/speclib.c:58:20: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
../include/speclib.c:59:15: warning: implicit declaration of function ‘strsep’; did you mean ‘strlen’? [-Wimplicit-function-declaration]
  while((key = strsep(&string,pairs_sep))) {
               ^~~~~~
               strlen
../include/speclib.c:59:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  while((key = strsep(&string,pairs_sep))) {
             ^
../include/speclib.c: In function ‘spec_normalization_pcfi’:
../include/speclib.c:76:24: error: ‘SIZE_MAX’ undeclared (first use in this function); did you mean ‘__SIZE_MAX__’?
  if(__builtin_expect(!(SIZE_MAX >> hn),0))
                        ^~~~~~~~
                        __SIZE_MAX__
../include/speclib.c:76:24: note: each undeclared identifier is reported only once for each function it appears in
In file included from ../include/speclib.h:1:0,
                 from ../include/speclib.c:1:
../include/speclib.c:77:21: error: ‘M_SQRT2’ undeclared (first use in this function)
   return mi(pow)(mi(M_SQRT2),n);
                     ^
../include/precision.h:72:19: note: in definition of macro ‘CAT_’
 #define CAT_(x,y) x##y
                   ^
../include/precision.h:77:18: note: in expansion of macro ‘CAT’
 #define mi(call) CAT(call,INTERMEDIATE_SUFFIX)
                  ^~~
../include/speclib.c:77:18: note: in expansion of macro ‘mi’
   return mi(pow)(mi(M_SQRT2),n);
                  ^~
../include/speclib.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-initializer-overrides’
Makefile:11: recipe for target 'speclib.o' failed
make[1]: *** [speclib.o] Error 1
make[1]: Leaving directory '/home/volodymyr/Desktop/Teezily/dspfun/scan'
Makefile:8: recipe for target 'scan' failed
make: *** [scan] Error 2

```

**Comment by 0x09** [comment]
@volodymyrkepsha all projects should now build correctly without any additional CFLAGS on linux/glibc as of  https://github.com/0x09/dspfun/commit/90c647a900c51f957e34044431c0524b88503d3c

**Comment by ghost** [comment]
@0x09 
Yes, now it did built without any problems. Thanks you for the support !
But, when I try to run '''' spec ''' command, I'm getting: _Command 'spec' not found_
Sorry for disturbing.

**Comment by 0x09** [comment]
@volodymyrkepsha no problem, all of the dspfun tools build into their own source directories; you can either install this manually by running e.g. `install spec/spec /usr/local/bin` (or your preferred path) as root or with sudo from the project dir, or just directly run `./spec` from the spec source directory.

I've treated this project as more of a playground of grab bag experiments/utilities than something to conventionally install on the system, but there's no real reason these Makefiles shouldn't have install targets to make doing so easier, so I'll create an issue to add those.

**Comment by ghost** [comment]
Thank you !
It works!!
